# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'mensajes' do
	pod 'JSQMessagesViewController'
	pod 'Firebase', '>= 2.2.2'
end

target 'mensajesTests' do

end

